---
config:
  layout: elk
---
flowchart TD
    SNOW_Account[fa:fa-building SNOW_Account]
    SNOW_Application[fa:fa-window-maximize SNOW_Application]
    SNOW_ApplicationRole[fa:fa-user-shield SNOW_ApplicationRole]
    SNOW_Database[fa:fa-database SNOW_Database]
    SNOW_Function[fa:fa-code SNOW_Function]
    SNOW_Integration[fa:fa-user-tie SNOW_Integration]
    SNOW_Procedure[fa:fa-cogs SNOW_Procedure]
    SNOW_Role[fa:fa-user-group SNOW_Role]
    SNOW_Schema[fa:fa-network-wired SNOW_Schema]
    SNOW_Stage[fa:fa-layer-group SNOW_Stage]
    SNOW_Table[fa:fa-table SNOW_Table]
    SNOW_User[fa:fa-user SNOW_User]
    SNOW_View[fa:fa-eye SNOW_View]
    SNOW_Warehouse[fa:fa-warehouse SNOW_Warehouse]

    style SNOW_Account fill:#5FED83
    style SNOW_Application fill:#A1C6EA
    style SNOW_ApplicationRole fill:#C6C3FF
    style SNOW_Database fill:#FF80D2
    style SNOW_Function fill:#A9E5E5
    style SNOW_Integration fill:#BFFFD1
    style SNOW_Procedure fill:#D8C8F8
    style SNOW_Role fill:#C06EFF
    style SNOW_Schema fill:#DEFEFA
    style SNOW_Stage fill:#80E0C6
    style SNOW_Table fill:#FFD2A6
    style SNOW_User fill:#FF8E40
    style SNOW_View fill:#A6E0FF
    style SNOW_Warehouse fill:#9EECFF
    
    SNOW_Account -.->|SNOW_Contains| SNOW_Application
    SNOW_Account -.->|SNOW_Contains| SNOW_ApplicationRole
    SNOW_Account -.->|SNOW_Contains| SNOW_Database
    SNOW_Account -.->|SNOW_Contains| SNOW_Function
    SNOW_Account -.->|SNOW_Contains| SNOW_Integration
    SNOW_Account -.->|SNOW_Contains| SNOW_Procedure
    SNOW_Account -.->|SNOW_Contains| SNOW_Role
    SNOW_Account -.->|SNOW_Contains| SNOW_Schema
    SNOW_Account -.->|SNOW_Contains| SNOW_Stage
    SNOW_Account -.->|SNOW_Contains| SNOW_Table
    SNOW_Account -.->|SNOW_Contains| SNOW_User
    SNOW_Account -.->|SNOW_Contains| SNOW_View
    SNOW_Account -.->|SNOW_Contains| SNOW_Warehouse
    
    SNOW_Application -.->|SNOW_Contains| SNOW_ApplicationRole
    SNOW_Application -.->|SNOW_ExecuteManagedTask| SNOW_Account
    SNOW_Application -.->|SNOW_ExecuteTask| SNOW_Account

    SNOW_ApplicationRole -.->|SNOW_Delete| SNOW_Table
    SNOW_ApplicationRole -.->|SNOW_Select| SNOW_Table
    SNOW_ApplicationRole -.->|SNOW_Select| SNOW_View
    SNOW_ApplicationRole -.->|SNOW_Truncate| SNOW_Table
    SNOW_ApplicationRole -.->|SNOW_Usage| SNOW_Database
    SNOW_ApplicationRole -.->|SNOW_Usage| SNOW_Procedure
    SNOW_ApplicationRole -.->|SNOW_Usage| SNOW_Schema
    
    SNOW_Database -.->|SNOW_Contains| SNOW_Schema
    
    SNOW_Schema -.->|SNOW_Contains| SNOW_Function
    SNOW_Schema -.->|SNOW_Contains| SNOW_Procedure
    SNOW_Schema -.->|SNOW_Contains| SNOW_Stage
    SNOW_Schema -.->|SNOW_Contains| SNOW_Table
    SNOW_Schema -.->|SNOW_Contains| SNOW_View

    SNOW_User -.->|SNOW_Usage| SNOW_Role

    SNOW_Role -.->|SNOW_CreateSchema| SNOW_Database
    SNOW_Role -.->|SNOW_Modify| SNOW_Database
    SNOW_Role -.->|SNOW_Ownership| SNOW_Database
    SNOW_Role -.->|SNOW_Usage| SNOW_Database

    SNOW_Role -.->|SNOW_Modify| SNOW_Schema
    SNOW_Role -.->|SNOW_Monitor| SNOW_Schema
    SNOW_Role -.->|SNOW_Ownership| SNOW_Schema
    SNOW_Role -.->|SNOW_Useage| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateAggregationPolicy| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateAlert| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateAuthenticationPolicy| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateDataset| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateDynamicTable| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateEventTable| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateExternalTable| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateFileFormat| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateFunction| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateGitRepository| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateIcebergTable| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateImageRepository| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateMaskingPolicy| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateMaterializedView| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateModel| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateNetworkRule| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateNotebook| SNOW_Schema
    SNOW_Role -.->|SNOW_CreatePackagesPolicy| SNOW_Schema
    SNOW_Role -.->|SNOW_CreatePasswordPolicy| SNOW_Schema
    SNOW_Role -.->|SNOW_CreatePipe| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateProcedure| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateProjectionPolicy| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateResourceGroup| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateRowAccessPolicy| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateSecret| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateSequence| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateService| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateServiceClass| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateSessionPolicy| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateSnapshot| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateStage| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateStream| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateStreamlit| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateTable| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateTag| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateTask| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateTemporaryTable| SNOW_Schema
    SNOW_Role -.->|SNOW_CreateView| SNOW_Schema
    SNOW_Role -.->|SNOW_ManageGrants| SNOW_Schema

    SNOW_Role -.->|SNOW_Ownership| SNOW_Integration
    SNOW_Role -.->|SNOW_Usage| SNOW_Integration
    SNOW_Role -.->|SNOW_UseAnyRole| SNOW_Integration

    SNOW_Role -.->|SNOW_Ownership| SNOW_Role
    SNOW_Role -.->|SNOW_Usage| SNOW_Role

    SNOW_Role -.->|SNOW_Ownership| SNOW_User

    SNOW_Role -.->|SNOW_Modify| SNOW_Warehouse
    SNOW_Role -.->|SNOW_Monitor| SNOW_Warehouse
    SNOW_Role -.->|SNOW_Operate| SNOW_Warehouse
    SNOW_Role -.->|SNOW_Ownership| SNOW_Warehouse
    SNOW_Role -.->|SNOW_Usage| SNOW_Warehouse

    SNOW_Role -.->|SNOW_AddSearchOptimization| SNOW_Schema
    SNOW_Role -.->|SNOW_AddSearchOptimization| SNOW_Schema

    SNOW_Role -.->|SNOW_Ownership| SNOW_Function
    SNOW_Role -.->|SNOW_Usage| SNOW_Function

    SNOW_Role -.->|SNOW_Ownership| SNOW_Procedure
    SNOW_Role -.->|SNOW_Usage| SNOW_Procedure

    SNOW_Role -.->|SNOW_Ownership| SNOW_Stage
    SNOW_Role -.->|SNOW_Read| SNOW_Stage
    SNOW_Role -.->|SNOW_Usage| SNOW_Stage
    SNOW_Role -.->|SNOW_Write| SNOW_Stage

    SNOW_Role -.->|SNOW_Delete| SNOW_Table
    SNOW_Role -.->|SNOW_Insert| SNOW_Table
    SNOW_Role -.->|SNOW_Ownership| SNOW_Table
    SNOW_Role -.->|SNOW_Rebuild| SNOW_Table
    SNOW_Role -.->|SNOW_References| SNOW_Table
    SNOW_Role -.->|SNOW_Select| SNOW_Table
    SNOW_Role -.->|SNOW_Truncate| SNOW_Table
    SNOW_Role -.->|SNOW_Update| SNOW_Table

    SNOW_Role -.->|SNOW_Delete| SNOW_View
    SNOW_Role -.->|SNOW_Insert| SNOW_View
    SNOW_Role -.->|SNOW_Ownership| SNOW_View
    SNOW_Role -.->|SNOW_Rebuild| SNOW_View
    SNOW_Role -.->|SNOW_References| SNOW_View
    SNOW_Role -.->|SNOW_Select| SNOW_View
    SNOW_Role -.->|SNOW_Truncate| SNOW_View
    SNOW_Role -.->|SNOW_Update| SNOW_View

%% Complete model